#! /bin/sh

# $Id$

# I use
# - autoconf (GNU Autoconf) 2.57
# - automake (GNU automake) 1.7.3
# - ltmain.sh (GNU libtool) 1.4.3 (1.922.2.111 2002/10/23 02:54:36)

ac_aux_dir=build

set -e
set -x

# some cleanup
if [ -e Makefile ]
then
  make distclean
fi
rm -f $ac_aux_dir/aclocal.m4 aclocal.m4
rm -f config.h.in
rm -rf autom4te.cache

aclocal -I $ac_aux_dir --output=$ac_aux_dir/aclocal.m4

libtoolize --copy --force
# cp -f ~/cvs/config/config.guess ~/cvs/config/config.sub build/

autoheader --include=$ac_aux_dir

# needed otherwise automake says
# no proper implementation of AM_INIT_AUTOMAKE was found,
ln -s $ac_aux_dir/aclocal.m4

autoconf --include=$ac_aux_dir #--warnings=all #--verbose
automake --add-missing --copy #--verbose

