#!/bin/sh

# $Id$

# restat from a clean base
if test -f Makefile
then
  make distclean
fi

autoreconf --force --localdir=build --verbose
./configure --prefix=/usr/local/

#./configure --prefix=/usr/local/ --enable-usb --enable-debug --enable-threadsafe --enable-runpid=/var/run/pcscd.pid --enable-usbdropdir=/usr/lib/pcsc/

