.TH UPDATE-READER.CONF 8 "Oct 2006"
.SH NAME
update\-reader.conf \- (re)generate /etc/reader.conf
.SH SYNOPSIS
.B update\-reader.conf
[force]
.SH DESCRIPTION
.B update\-reader.conf
is a simple tool to manage
.IR /etc/reader.conf .
The PCSC daemon (pcscd) uses one configuration file for its
configuration. This makes it hard for packages to dynamically add
information about their own smart card reader drivers. To fix this
.B
update\-reader.conf
has been introduced.
.PP
.B update-reader.conf
attempts to fix this by generating the configuration file from seperate
files which are located in
.IR /etc/reader.conf.d/ .
All files in that directory are assembled together to form
.IR /etc/reader.conf .
.SH "FILES"
.B update\-reader.conf
will only use files that match the following wildcard:
.BR *.conf .
.SH "SEE ALSO"
.BR pcscd (1), reader.conf (5)
.SH AUTHOR
This manual page was written by Ludovic Rousseau
<ludovic.rousseau@free.fr>.
